export default {
    VERDAD: [
        '¿CUANDO DISTE TU PRIMER BESO?',
        '¿TE GUSTAN LAS PERSONAS DE TU MISMO SEXO?',
        '¿A QUE EDAD PERDISTE LA VIRGINIDAD?',
        '¿HAS DADO SEXO ORAL?',
        '¿TE GUSTA ALGUNO DE LOS JUGADORES PRESENTES?',
        '¿FUISTE INFIEL ALGUNA VEZ?'
    ],
    RETO: [
        'DALE UN BESO A QUIEN TIENES A TU LADO',
        'QUITATE UNA PRENDA',
        'NALGUEA A UNO DE TUS AMIGOS',
        'DEBES HACER 15 FLEXIONES',
        'BESA ALGUIEN DE TU MISMO SEXO',
        'METE LA LENGUA EN EL OIDO DE UNO DE LOS JUGADORES'
    ],
}